/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        "on-primary": "#ffffff",
        "on-surface-variant": "#44474e",
        "border-subtle": "#E2E8F0",
        "primary-fixed": "#d8e2ff",
        error: "#ba1a1a",
        primary: "#031635",
        "surface-dim": "#d8dadc",
        "on-background": "#191c1e",
        "on-secondary-container": "#2e5484",
        background: "#f7f9fb",
        "surface-tint": "#4e5e81",
        "surface-variant": "#e0e3e5",
        "on-primary-container": "#8293b8",
        "outline-variant": "#c5c6cf",
        "tertiary-container": "#3e2700",
        "error-container": "#ffdad6",
        secondary: "#3b6090",
        "secondary-fixed": "#d4e3ff",
        "inverse-surface": "#2d3133",
        "legal-text": "#2D3748",
        tertiary: "#231400",
        "on-tertiary": "#ffffff",
        "primary-fixed-dim": "#b6c6ef",
        "surface-container-high": "#e6e8ea",
        "surface-container-low": "#f2f4f6",
        "on-tertiary-fixed": "#291800",
        "success-green": "#38A169",
        outline: "#75777f",
        "on-error": "#ffffff",
        "on-tertiary-fixed-variant": "#5d4217",
        "surface-bright": "#f7f9fb",
        "surface-container": "#eceef0",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed-variant": "#364768",
        "primary-container": "#1a2b4b",
        surface: "#f7f9fb",
        "on-primary-fixed": "#081b3a",
        "secondary-fixed-dim": "#a5c8ff",
        "critical-red": "#E53E3E",
        "surface-container-highest": "#e0e3e5",
        "on-tertiary-container": "#b08d5b",
        "tertiary-fixed": "#ffddb1",
        "on-secondary-fixed-variant": "#204877",
        "warning-gold": "#D69E2E",
        "inverse-primary": "#b6c6ef",
        "on-error-container": "#93000a",
        "on-surface": "#191c1e",
        "on-secondary": "#ffffff",
        "on-secondary-fixed": "#001c3a",
        "tertiary-fixed-dim": "#e8c08a",
        "inverse-on-surface": "#eff1f3",
        "secondary-container": "#a5c8ff",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        gutter: "16px",
        unit: "4px",
        "section-gap": "32px",
        "card-padding": "20px",
        "container-padding": "24px",
      },
      fontFamily: {
        "label-bold": ["Inter"],
        "mono-legal": ["Inter"],
        "headline-md": ["Inter"],
        "label-sm": ["Inter"],
        "body-lg": ["Inter"],
        "headline-sm": ["Inter"],
        "body-md": ["Inter"],
        "display-lg": ["Inter"],
      },
      fontSize: {
        "label-bold": ["14px", { lineHeight: "20px", fontWeight: "600" }],
        "mono-legal": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "display-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};
